Grading queue: Reservation conflicts
GeorgeRay/DavisTechCanvasAPIApp pull request #40
Opened 2021-02-03 18:33 UTC by cheeseonamonkey

I'm not sure that this is how we want it exactly, but it's a start.

It will now bring the app into focus before displaying the "already reserved" message, and simply close the grading tab we just opened. You should be able to see whats going on easily just by the diff.

I was able to connect Mongo last night but I'm having issues with it on a different computer today, so I haven't tested these all together, I have figure out what's going on there.

2021-02-03 18:44 UTC, cheeseonamonkey commented
Also threw in code for issue #38 (unreserving another's assignment). Will now ask if you're sure you want to uncheck the reservation box

2021-02-04 18:06 UTC, cheeseonamonkey commented
On second thought it is seems obviously much better to only open the URL if the database write was successful rather than to open it regardless and sometimes close it.

Although this will essentially require a Mongo connection to let you use the checkbox as a link to grade the assignment. I think this is fine because there is already a link in teh same row by clicking the assignment name. If we'd still like the checkbox to work as a link without a Mongo connection it would be easy to implement but I don't think its necessary.

2021-02-04 18:27 UTC, cheeseonamonkey commented
That should resolve issue #36 while I'm here too

2021-02-04 20:00 UTC, GeorgeRay requested changes
Open browser first. Then write to database.

2021-02-05 18:25 UTC, merged

2021-02-05 18:26 UTC, GeorgeRay commented
I wanted to pull in the last changes and publish the latest version. I will fix my last request.